Repository AY2324S1-CS2103T-W16-2/tp, pull requests merged in 2023-10, with the labels that each got.

#36 Modify AboutUs for Joshua's details
  docs/AboutUs.md
  docs/images/joshuawee.png
Labels: About Us

#37 Update User Guide
  docs/UserGuide.md
Labels: UG

#42 Create PPP skeletal for songfangyl
  docs/team/songfangyl.md
Labels: PPP

#43 Update aboutUs
  docs/AboutUs.md
  docs/images/songfangyl.png
Labels: About Us

#41 Update UserGuide for Delete
  docs/UserGuide.md
Labels: UG

#55 Update Developer Guide
  docs/DeveloperGuide.md
Labels: DG

#77 Modify List feature to disallow parameters
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Epic, priority.High

#96 Fix bug of equals method in address
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/EmptyAddress.java
  src/test/java/seedu/address/model/person/AddressTest.java
Labels: type.Bug

#99 Modify User Guide List feature
  docs/UserGuide.md
Labels: UG, type.Epic, priority.High

#123 Add size to output of list feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: priority.Medium

#174 Update DG for Appointment feature
  docs/DeveloperGuide.md
Labels: DG
